Repository hmcts/rd-commondata-api, pull requests merged in 2021-12, with the labels that each got.

#10 Added Database configuration
  bin/init.sh
  bin/run-in-docker.sh
  build.gradle
  charts/rd-commondata-api/Chart.yaml
  charts/rd-commondata-api/values.preview.template.yaml
  charts/rd-commondata-api/values.yaml
  database/Dockerfile
  database/init-db.sh
  docker-compose.yml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_1__init_tables.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-10

#12 added /rd/ to the import statement [ minor update]
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-12

#14 Feat:Create new table and insert data for Flag Details
  src/main/resources/db/migration/V1_2__init_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-14

#22 Fix env issue
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-22

#23 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-23

#13 RDCC-3713: Create a new table for Hearing Channel
  src/main/resources/db/migration/V1_3__insert_hearing_channel.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-13

#25 Feat:Create a new View for LOV
  src/main/resources/db/migration/V1_4__create_view_mv_list_of_values .sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-25

#27 fix: patch log4j to the 2.16.0 in all applications to fix CVE-2021-45046
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-27

#31 fix: RDCC-3808 added enableDbMigration jenkins stage and updated the versions
  Jenkinsfile_CNP
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-31

#33 fix: Added postgres port secret config
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-33

#37 fix: CVE-2021-45105 by upgrading log4j to 2.17.0
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-37
