Repository hmcts/rd-commondata-api, pull requests merged in 2022-02, with the labels that each got.

#57 Commits to support Gradle 7.3.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-57

#66 Update flag_details.sql
  src/main/resources/db/migration/V1_8__insert_flag_details_and_service.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-66

#74 fixed sonar issues
  src/main/java/uk/gov/hmcts/reform/cdapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/CaseFlagTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/FlagDetailTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/FlagTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/exception/CommonDataApiExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/exception/InvalidRequestExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/exception/ResourceNotFoundExceptionTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-74

#76 RDCC-4048: Fix CVEs
  audit.json
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-76

#55 RDCC-3947: Fixing CVE
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-55

#75 simplified flyway scripts
  src/main/resources/db/migration/V1_1__init_tables.sql
  src/main/resources/db/migration/V1_2__create_view_mv_list_of_values .sql
  src/main/resources/db/migration/V1_2__init_table_flag_details.sql
  src/main/resources/db/migration/V1_3__insert_hearing_channel.sql
  src/main/resources/db/migration/V1_5__insert_additional_facilities.sql
  src/main/resources/db/migration/V1_6__update_view_mv_list_of_values.sql
  src/main/resources/db/migration/V1_7__update_entity_role_codes.sql
  src/main/resources/db/migration/V1_8__insert_flag_details_and_service.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-75

#73 handled idam bearer token exception
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagByServiceIdFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/RestAuthenticationEntryPoint.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityConfiguration.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-73

#82 fix: Bump base java helm chart to 3.7.1
  charts/rd-commondata-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-82

#83 RDCC-4088 Fix nightly build failure due to CWE-862: Missing Authorization
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-83

#81 Rdcc 3965
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/cdapi/provider/CommonDataApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/RetrieveHearingChannelsByCategoryKeyFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/RetrieveListOfValuesByCategoryKeyFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/client/CommonDataApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiController.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/request/CategoryRequest.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/response/Categories.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/response/Category.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/ListOfValueDto.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecification.java
  src/main/java/uk/gov/hmcts/reform/cdapi/repository/HearingChannelRepository.java
  src/main/java/uk/gov/hmcts/reform/cdapi/repository/ListOfValuesRepository.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/CrdService.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/FeatureToggleServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecificationTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/helper/CrdTestSupport.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-81
