Repository hmcts/rd-commondata-api, pull requests merged in 2022-09, with the labels that each got.

#205 adding suppression for CVE-2022-25857
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-205

#203 Insert value in to Flag Details Table
  src/integrationTest/resources/db/testmigration/V1_8__Insert_table_flag_details.sql
  src/integrationTest/resources/db/testmigration/V1_9__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_9__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-203

#206 fix: RDCC-5447 Suppress CVEs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-206

#211 Nightly Fix: Updating security.sh
  security.sh
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-211

#219 CVE Issues
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-219
