Repository hmcts/rd-commondata-api, pull requests merged in 2022-07, with the labels that each got.

#189 RDCC-5016: Adding Suppression for CVE-2022-33915
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-189

#191 config: RDCC-5041 Upgrade java chart
  charts/rd-commondata-api/Chart.yaml
  charts/rd-commondata-api/values.preview.template.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-191

#194 RDCC-5145 Upgrade java chart version
  charts/rd-commondata-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-194

#193 Feat:RDCC-4997:Changes made to add and fix checkstyle
  config/fortify-client.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-193

#195 RDCC-5162 Delete dependabot yaml file
  .github/dependabot.yml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-195
