Repository hmcts/rd-commondata-api, pull requests merged in 2022-06, with the labels that each got.

#162 Feat:To handle 500 HTTP responses
  src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/cdapi/exception/UnauthorizedException.java
  src/main/java/uk/gov/hmcts/reform/cdapi/repository/IdamRepository.java
  src/test/java/uk/gov/hmcts/reform/cdapi/exception/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/repository/IdamRepositoryTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-162

#170 config: RDCC-4822 Configured renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-170

#171 Feat:RDCC-4676:Changes made to Auto merge depend Bot script w.r.t Renovate
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-171

#172 RDCC-4849: Collating DependaBot PRs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-172

#183 RDCC-4906 CRD : Test Flag Details Changes
  src/main/resources/db/migration/V1_8__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-183

#184 RDCC-4906 CRD : Test Flag Details Changes
  src/main/resources/db/migration/V1_8__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-184

#188 RDCC-5007: Adding Suppression for `CVE-2022-34305`
  charts/rd-commondata-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-188
