Repository hmcts/rd-commondata-api, pull requests merged in 2022-04, with the labels that each got.

#115 RDCC-4402: CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-115

#121 RDCC-4427: CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-121

#135 commondata -Nightly build failure -25/04/2022
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-135

#117 include common-libs
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/SerenityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/SerenityTestWithoutReporting.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/counter/TestCountListener.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/counter/TestCounter.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/SerenityExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/SerenityJUnitLifecycleAdapterExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/SerenityManualExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/SerenityReportExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/SerenityStepExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/page/SerenityPageExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/page/TestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/extension/page/TestMethodAnnotations.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/guice/JUnit5Module.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/serenity5/guice/JUnitInjectors.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-117

#118 RDCC-4352:Changes made to upgrade for java17
  Dockerfile
  build.gradle
  docker-compose.yml
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecificationTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/repository/CaseFlagRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/repository/IdamRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/repository/ListOfVenueRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-118

#138 Nightly Fix: Increasing Mutation Versions
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-138
