Repository hmcts/rd-commondata-api, pull requests merged in 2022-11, with the labels that each got.

#227 RDCC-5778: Upgrading `tomcat` to version `9.0.68`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-227

#229 Revert "updated flag details"
  src/integrationTest/resources/db/testmigration/V1_10__update_table_flag_details.sql
  src/main/resources/db/migration/V1_10__update_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-229

#232 Case Flags : Add two new columns in Flag Service table : Rdcc 5571
  src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-232

#233 RDCC-5853: enabling Fortify Scan
  Jenkinsfile_nightly
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-233

#234 Revert "Case Flags : Add two new columns in Flag Service table : Rdcc 5571 "
  src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-234

#237 Case Flags : Add two new columns in Flag Service table : Rdcc 5571
  src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-237

#236 RDCC-5853: Fix - Syncing Fortify Config with PRD
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-236

#231 RDCC-5741:updated flag details
  src/integrationTest/resources/db/testmigration/V1_10__update_table_flag_details.sql
  src/main/resources/db/migration/V1_10__update_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-231

#239 Revert "Case Flags : Add two new columns in Flag Service table : Rdcc 5571 "
  src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-239

#238 Revert "RDCC-5741:updated flag details"
  src/integrationTest/resources/db/testmigration/V1_10__update_table_flag_details.sql
  src/main/resources/db/migration/V1_10__update_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-238

#241 Revert "Revert "Case Flags : Add two new columns in Flag Service table : Rdcc 5571 ""
  src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-241

#242 Change the flyway script as there is conflict with the sequence numbe…
  src/integrationTest/resources/db/testmigration/V1_12__update_table_flag_details.sql
  src/main/resources/db/migration/V1_12__update_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-242

#243 Upgrade Terraform version 1.3.X :: RDCC-5894
  infrastructure/.terraform-version
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-243

#240 RDCC-5815-Common data api - Test coverage with BDD Approach
  build.gradle
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-240

#246 RDCC-5914-flag details inserts
  src/integrationTest/resources/db/testmigration/V1_13__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_13__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-246

#247 CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-247
