Repository hmcts/rd-commondata-api, pull requests merged in 2022-05, with the labels that each got.

#146 fix for CVE 2022-25647
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-146

#142 New values insertion of flag details table
  src/main/resources/db/migration/V1_6__Alter_List_Of_Values.sql
  src/main/resources/db/migration/V1_7__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-142

#145 Feat:Changes made to fix app-insights issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-145

#150 Implement the Lib segregation for API related to Bearer tokens and fo…
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/client/CommonDataApiClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/client/S2sClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/config/TestConfigProperties.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/idam/IdamOpenIdClient.java
  src/functionalTest/resources/application-functional.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-150

#153 RDCC-4690: Suppressing CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-153

#157 fix: Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-157
