Repository hmcts/rd-commondata-api, pull requests merged in 2023-03, with the labels that each got.

#280 RDCC-6464: Adding Suppression for `CVE-2023-24998`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-280

#277 RDCC-6421-renovate.json update
  .github/renovate.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-277

#281 RDCC-6502 Upgrade Libs in CRD API
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
  src/test/java/uk/gov/hmcts/reform/cdapi/repository/IdamRepositoryTest.java
Labels: ns:rd, prd:rd, no-changes, rel:rd-commondata-api-pr-281

#282 Feat:Address CVEs in all Reference Data repositories - Common Reference Data
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-282

#285 RDCC-6611: suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-285

#284 Updated the gradle wrapper to 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-284

#286 addresses nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-286

#283 RDCC-6528-Address Sonar Coverage issues
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiController.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiController.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/RootController.java
  src/main/java/uk/gov/hmcts/reform/cdapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-283

#289 RDCC-6682: suppress CVE-2023-20861
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-289
