Repository hmcts/rd-commondata-api, pull requests merged in 2023-08, with the labels that each got.

#317 DTSRD-1075: Add Native flag code to payload
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/CaseFlagDto.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/FlagDetail.java
  src/main/java/uk/gov/hmcts/reform/cdapi/repository/CaseFlagRepository.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/CaseFlagDtoTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/FlagDetailTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-317

#318 DTSRD-1173
  audit.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-318

#319 DTSRD-1173
  audit.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-319

#320 DTSRD-1173
  audit.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-320
