Repository hmcts/rd-commondata-api, pull requests merged in 2023-01, with the labels that each got.

#260 RDCC-6118: Adding suppression for `CVE-2021-4277`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-260

#261 RDCC-6130: Adding suppressions for `CVE-2022-3064` & `CVE-2021-4235`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-261

#259 Rdcc 5572 update case flags api
  build.gradle
  config/owasp/suppressions.xml
  src/contractTest/java/uk/gov/hmcts/reform/cdapi/provider/CommonDataApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/client/CommonDataApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/util/CommonDataApiClient.java
  src/integrationTest/resources/db/testmigration/V1_12__update_table_flag_details.sql
  src/integrationTest/resources/db/testmigration/V1_6__Alter_List_Of_Values.sql
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiController.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/CaseFlagDto.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/FlagDetail.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/ListOfValue.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/jsonfilter/IgnoreJsonFilter.java
  src/main/java/uk/gov/hmcts/reform/cdapi/repository/CaseFlagRepository.java
  src/main/java/uk/gov/hmcts/reform/cdapi/repository/ListOfVenueRepository.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/CaseFlagService.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cdapi/util/ValidationUtil.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/util/ValidationUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-259

#262 RDCC-6139: Upgrading Tomcat to `9.0.69` to fix `CVE-2022-45143`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-262

#263 security
  audit.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-263

#264 sonar fixes
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-264

#265 RDCC-6142: Adding entry to `audit.json` to fix Nightly Build
  audit.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-265
