Repository hmcts/rd-commondata-api, pull requests merged in 2023-10, with the labels that each got.

#332 DTSRD-1234.Upgrade Postgresss to V15
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, destroy, rel:rd-commondata-api-pr-332

#336 DTSRD-1213.reverting the changes done for upgrade to postgresV15
  database/Dockerfile
  infrastructure/main.tf
  infrastructure/provider.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, destroy, rel:rd-commondata-api-pr-336

#342 DTSRD-1234 Upgrade to V15
  infrastructure/main.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-commondata-api-pr-342

#343 DTSRD-1234 Upgrade to V15
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-commondata-api-pr-343

#344 DTSRD-1234
  infrastructure/output.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-commondata-api-pr-344

#365 DTSRD-1466.Remove branches to sync -commondata demo and master
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-365

#369 Addresses CVE-2023-42794, CVE-2023-42795 and CVE-2023-45648
  build.gradle
  charts/rd-commondata-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-369

#378 suppress CVE-2023-5072
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-378
