Repository hmcts/rd-commondata-api, pull requests merged in 2023-06, with the labels that each got.

#305 removed suppression
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-305

#307 DTSRD-552: Fix CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-307

#308 Renovate config
  .github/renovate.json
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-308

#306 Update README.md
  README.md
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-306

#311 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-311
