Repository hmcts/rd-commondata-api, pull requests merged in 2023-05, with the labels that each got.

#297 Enhance rd-commondata-api integration test cases
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-297

#299 addresses CVE-2023-20873, CVE-2023-20862
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-299

#301 Updating Case Flag Details
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-301

#303 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-303

#304 DTSRD-456: fix CVE-2023-28709
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-304
