Repository hmcts/rd-commondata-api, pull requests merged in 2024-10, with the labels that each got.

#590 DTSRD-3562 Swagger Publishing
  .github/workflows/swagger.yml
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/config/SwaggerPublisherTest.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-590

#591 DTSRD-3580 Jenkins Test Reports to Publish on Failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-591

#592 DTSRD-3619
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-592

#593 DTSRD-3583 PI Test Version Config - pitestVersion added to pitest con…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-593
