Repository hmcts/rd-commondata-api, pull requests merged in 2024-06, with the labels that each got.

#504 DTSRD-2895
  infrastructure/provider.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-commondata-api-pr-504

#518 Update build.gradle
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-518

#519 Update gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-519

#520 Fix Build -data changed-fix- Update CommonDataApiFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-520

#521 fixing build
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-521

#492 DTSRD-2215.Fixing query to fetch listof values category by service id
  Jenkinsfile_CNP
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_6__Alter_List_Of_Values.sql
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecification.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecificationTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, aat/no-changes, demo/add-or-update, rel:rd-commondata-api-pr-492
