Repository hmcts/rd-commondata-api, pull requests merged in 2024-07, with the labels that each got.

#523 DTSRD-3041
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-523

#525 Dtsrd 3090
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/provider.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-commondata-api-pr-525

#524 Dtsrd 3041
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-524

#310 DTSRD-59: Upgrade spring boot for rd-commondata-api
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  gradle.properties
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/AuthorizationFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/util/CommonDataApiClient.java
  src/main/java/uk/gov/hmcts/reform/cdapi/CommonDataApplication.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/CacheConfig.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/FeatureConditionEvaluation.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/LaunchDarklyClientConfig.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/RestAuthenticationEntryPoint.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/cdapi/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiController.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/CaseFlag.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/CaseFlagDto.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/CategoryKey.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/ListOfValue.java
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/ListOfValueDto.java
  src/main/java/uk/gov/hmcts/reform/cdapi/exception/handler/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/FeatureToggleServiceImpl.java
  src/main/resources/testcontainers.properties
  src/test/java/uk/gov/hmcts/reform/cdapi/config/FeatureConditionEvaluationTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecificationTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-310

#539 Fix build mutation
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-539
