Repository hmcts/rd-commondata-api, pull requests merged in 2024-03, with the labels that each got.

#439 DTSRD-2065-3.Schema Owner Fix
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, no-changes, rel:rd-commondata-api-pr-439

#441 DTSRD-2215.Fixing query to fetch listof values category by service id
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_6__Alter_List_Of_Values.sql
  src/main/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecification.java
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-441

#450 Fix CVE-2024-1597
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-450
