Repository hmcts/rd-commondata-api, pull requests merged in 2025-01, with the labels that each got.

#605 CME-248: Database monitoring and alerting on RD repositories
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-commondata-api-pr-605

#607 CME-301: Update azurerm
  infrastructure/provider.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-commondata-api-pr-607

#608 Update to spring-boot 3.3.7
  build.gradle
Labels: ns:rd, prd:rd

#602 CME-197 bump rd-commons-lib
  .github/workflows/ci.yml
  .github/workflows/swagger.yml
  Dockerfile
  README.md
  acb.tpl.yaml
  build.gradle
  config/owasp/suppressions.xml
  database/Dockerfile
  gradle/wrapper/gradle-wrapper.properties
  src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/CdAuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/util/CommonDataApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/cdapi/util/CommonDataApiPostgresqlContainer.java
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/cdapi/CommonDataApplication.java
  src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiController.java
  src/smokeTest/java/uk/gov/hmcts/reform/cdapi/SmokeTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/config/FeatureConditionEvaluationTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/exception/handler/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/FeatureToggleServiceImplTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-commondata-api-pr-602

#613 Update HMCTS gradle plugin to 0.12.64
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-api-pr-613
